env:
    # Config
    CONFIG: CI_config.sh

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "TWRP Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:latest
      cpu: 8
      memory: 20G

  Sync_script:
     - curl -sL https://raw.githubusercontent.com/almondnguyen/twrp_device_samsung_a01core/twrp-12.1/CI_scripts/sync.sh | bash

  Build_script:
     - curl -sL https://raw.githubusercontent.com/almondnguyen/twrp_device_samsung_a01core/twrp-12.1/CI_scripts/build.sh | bash

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - curl -sL  https://raw.githubusercontent.com/almondnguyen/twrp_device_samsung_a01core/twrp-12.1/CI_scripts/upload.sh | bash
